/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lock.ca_projeto;
import java.util.Map;
import java.awt.font.TextAttribute;
import javax.swing.*;
import java.awt.*;
import javax.swing.border.Border;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author pivis
 */
public class PaginaLogin extends javax.swing.JFrame {

    private Border FlatTextBorder;

    /**
     * Creates new form PaginaInicial
     */
    public PaginaLogin() {
        initComponents();
        button_login.setFocusPainted(false);
        button_cadastrar.setFocusPainted(false);
        button_confirmar.setFocusPainted(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        header_icon = new javax.swing.JPanel();
        icon_label_maua = new javax.swing.JLabel();
        icone_min_max_close = new javax.swing.JPanel();
        button_min = new javax.swing.JPanel();
        max_panel = new javax.swing.JPanel();
        button_max = new javax.swing.JLabel();
        close_panel = new javax.swing.JPanel();
        button_sair = new javax.swing.JLabel();
        login_cadastro_panel = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        button_login = new javax.swing.JButton();
        button_cadastro = new javax.swing.JPanel();
        button_cadastrar = new javax.swing.JButton();
        button_confirmar = new javax.swing.JButton();
        email_label = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        password_field_login = new javax.swing.JPasswordField();
        email_field = new javax.swing.JTextField();
        Nome_logo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Header.setBackground(new java.awt.Color(0, 0, 0));
        Header.setPreferredSize(new java.awt.Dimension(800, 50));
        Header.setLayout(new java.awt.BorderLayout());

        header_icon.setBackground(new java.awt.Color(0, 0, 0));
        header_icon.setPreferredSize(new java.awt.Dimension(200, 100));
        header_icon.setLayout(new java.awt.BorderLayout());

        icon_label_maua.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        icon_label_maua.setForeground(new java.awt.Color(255, 255, 255));
        icon_label_maua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_label_maua.setText("MAUÁ");
        icon_label_maua.setPreferredSize(new java.awt.Dimension(20, 10));
        header_icon.add(icon_label_maua, java.awt.BorderLayout.CENTER);

        Header.add(header_icon, java.awt.BorderLayout.LINE_START);

        icone_min_max_close.setBackground(new java.awt.Color(0, 0, 0));
        icone_min_max_close.setPreferredSize(new java.awt.Dimension(150, 50));
        icone_min_max_close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_min.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout button_minLayout = new javax.swing.GroupLayout(button_min);
        button_min.setLayout(button_minLayout);
        button_minLayout.setHorizontalGroup(
            button_minLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        button_minLayout.setVerticalGroup(
            button_minLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        icone_min_max_close.add(button_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        max_panel.setBackground(new java.awt.Color(0, 0, 0));
        max_panel.setPreferredSize(new java.awt.Dimension(50, 50));
        max_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                max_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                max_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                max_panelMouseExited(evt);
            }
        });
        max_panel.setLayout(new java.awt.BorderLayout());

        button_max.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button_max.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/full_screen_32px.png"))); // NOI18N
        max_panel.add(button_max, java.awt.BorderLayout.CENTER);

        icone_min_max_close.add(max_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        close_panel.setBackground(new java.awt.Color(0, 0, 0));
        close_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close_panelMouseExited(evt);
            }
        });
        close_panel.setLayout(new java.awt.BorderLayout());

        button_sair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete_32px.png"))); // NOI18N
        close_panel.add(button_sair, java.awt.BorderLayout.CENTER);

        icone_min_max_close.add(close_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 50));

        Header.add(icone_min_max_close, java.awt.BorderLayout.LINE_END);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        login_cadastro_panel.setBackground(new java.awt.Color(73, 128, 242));
        login_cadastro_panel.setToolTipText("");
        login_cadastro_panel.setPreferredSize(new java.awt.Dimension(500, 450));

        login.setBackground(new java.awt.Color(73, 128, 242));
        login.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        login.setToolTipText("");
        login.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        login.setOpaque(false);
        login.setPreferredSize(new java.awt.Dimension(100, 100));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_login.setBackground(new java.awt.Color(73, 128, 242));
        button_login.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        button_login.setText("LOGIN");
        button_login.setToolTipText("");
        button_login.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        button_login.setBorderPainted(false);
        button_login.setContentAreaFilled(false);
        button_login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button_login.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        button_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_loginMouseExited(evt);
            }
        });
        login.add(button_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 62, -1, 40));

        button_cadastro.setBackground(new java.awt.Color(72, 128, 242));
        button_cadastro.setMinimumSize(new java.awt.Dimension(200, 50));
        button_cadastro.setPreferredSize(new java.awt.Dimension(300, 100));
        button_cadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_cadastrar.setBackground(new java.awt.Color(73, 128, 242));
        button_cadastrar.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        button_cadastrar.setText("CADASTRAR");
        button_cadastrar.setBorder(null);
        button_cadastrar.setBorderPainted(false);
        button_cadastrar.setContentAreaFilled(false);
        button_cadastrar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        button_cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_cadastrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_cadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_cadastrarMouseExited(evt);
            }
        });
        button_cadastro.add(button_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 150, 30));

        button_confirmar.setBackground(new java.awt.Color(73, 128, 242));
        button_confirmar.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        button_confirmar.setText("confirmar");
        button_confirmar.setActionCommand("");
        button_confirmar.setBorder(null);
        button_confirmar.setBorderPainted(false);
        button_confirmar.setContentAreaFilled(false);
        button_confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_confirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_confirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_confirmarMouseExited(evt);
            }
        });
        button_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_confirmarActionPerformed(evt);
            }
        });

        email_label.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        email_label.setText("Email constitucional :");

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel7.setText("Senha :");

        password_field_login.setBackground(new java.awt.Color(0, 0, 0));
        password_field_login.setForeground(new java.awt.Color(255, 255, 255));

        email_field.setBackground(new java.awt.Color(0, 0, 0));
        email_field.setForeground(new java.awt.Color(255, 255, 255));
        email_field.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout login_cadastro_panelLayout = new javax.swing.GroupLayout(login_cadastro_panel);
        login_cadastro_panel.setLayout(login_cadastro_panelLayout);
        login_cadastro_panelLayout.setHorizontalGroup(
            login_cadastro_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_cadastro_panelLayout.createSequentialGroup()
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(login_cadastro_panelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(login_cadastro_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(password_field_login)
                    .addComponent(email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(login_cadastro_panelLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(button_confirmar))
                    .addComponent(email_field))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        login_cadastro_panelLayout.setVerticalGroup(
            login_cadastro_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_cadastro_panelLayout.createSequentialGroup()
                .addGroup(login_cadastro_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_field_login, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_confirmar)
                .addGap(141, 141, 141))
        );

        getContentPane().add(login_cadastro_panel, java.awt.BorderLayout.LINE_START);

        Nome_logo.setBackground(new java.awt.Color(73, 128, 242));
        Nome_logo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 48)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("LOCKC.A");
        jLabel8.setToolTipText("");
        Nome_logo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 130, 50));

        jLabel1.setBackground(new java.awt.Color(73, 128, 242));
        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Empréstimo online de materiais ");
        Nome_logo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 270, 30));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        jLabel2.setText("esportivos do Centro Acadêmico");
        Nome_logo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 270, -1));

        getContentPane().add(Nome_logo, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(950, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_confirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_confirmarActionPerformed

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
    
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_loginMouseExited

    private void button_cadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_cadastrarMouseEntered
         Font originalFont = button_cadastrar.getFont();
        Map attributes = originalFont.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        button_cadastrar.setFont(originalFont.deriveFont(attributes));                                         
    }//GEN-LAST:event_button_cadastrarMouseEntered

    private void button_cadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_cadastrarMouseExited
        Font originalFont = button_cadastrar.getFont();
        Map attributes = originalFont.getAttributes();
        attributes.put(TextAttribute.UNDERLINE,-1);
        button_cadastrar.setFont(originalFont.deriveFont(attributes));
    }//GEN-LAST:event_button_cadastrarMouseExited
    public void  changecolor(JPanel hover , Color rand){
        hover.setBackground(rand);
    }
    private void close_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_panelMouseEntered
        changecolor(close_panel, new Color(19,19,19));
    }//GEN-LAST:event_close_panelMouseEntered

    private void close_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_panelMouseExited
        changecolor(close_panel,new Color (0,0,0));
    }//GEN-LAST:event_close_panelMouseExited

    private void close_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_panelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_close_panelMouseClicked

    private void max_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max_panelMouseEntered
        changecolor(max_panel, new Color(19,19,19));
    }//GEN-LAST:event_max_panelMouseEntered

    private void max_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max_panelMouseExited
        changecolor(max_panel,new Color (0,0,0));
    }//GEN-LAST:event_max_panelMouseExited

    private void max_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max_panelMouseClicked
         if(this.getExtendedState()!= PaginaLogin.MAXIMIZED_BOTH){
             this.setExtendedState(PaginaLogin.MAXIMIZED_BOTH);
         }
         else{
             this.setExtendedState(PaginaLogin.NORMAL);
         }
    }//GEN-LAST:event_max_panelMouseClicked

    private void button_cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_cadastrarMouseClicked
        PaginaRegistro mi = new PaginaRegistro();
                    mi.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_button_cadastrarMouseClicked

    private void button_confirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_confirmarMouseClicked
         PaginaMateriais mi = new PaginaMateriais();
                    mi.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_button_confirmarMouseClicked

    private void button_confirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_confirmarMouseEntered
        Font originalFont = button_confirmar.getFont();
        Map attributes = originalFont.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        button_confirmar.setFont(originalFont.deriveFont(attributes)); 
    }//GEN-LAST:event_button_confirmarMouseEntered

    private void button_confirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_confirmarMouseExited
       Font originalFont = button_confirmar.getFont();
       Map attributes = originalFont.getAttributes();
       attributes.put(TextAttribute.UNDERLINE,-1);
       button_confirmar.setFont(originalFont.deriveFont(attributes));
    }//GEN-LAST:event_button_confirmarMouseExited

    private void button_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_loginMouseExited
        Font originalFont = button_login.getFont();
        Map attributes = originalFont.getAttributes();
        attributes.put(TextAttribute.UNDERLINE,-1);
        button_login.setFont(originalFont.deriveFont(attributes));
    }//GEN-LAST:event_button_loginMouseExited

    private void button_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_loginMouseEntered
        Font originalFont = button_login.getFont();
        Map attributes = originalFont.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        button_login.setFont(originalFont.deriveFont(attributes));
    }//GEN-LAST:event_button_loginMouseEntered
    
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Nome_logo;
    private javax.swing.JButton button_cadastrar;
    private javax.swing.JPanel button_cadastro;
    private javax.swing.JButton button_confirmar;
    private javax.swing.JButton button_login;
    private javax.swing.JLabel button_max;
    private javax.swing.JPanel button_min;
    private javax.swing.JLabel button_sair;
    private javax.swing.JPanel close_panel;
    private javax.swing.JTextField email_field;
    private javax.swing.JLabel email_label;
    private javax.swing.JPanel header_icon;
    private javax.swing.JLabel icon_label_maua;
    private javax.swing.JPanel icone_min_max_close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel login;
    private javax.swing.JPanel login_cadastro_panel;
    private javax.swing.JPanel max_panel;
    private javax.swing.JPasswordField password_field_login;
    // End of variables declaration//GEN-END:variables
}
