/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lock.ca_projeto;
import java.util.Map;
import java.awt.font.TextAttribute;
import javax.swing.*;
import java.awt.*;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author pivis
 */
public class PaginaAluno extends javax.swing.JFrame {

    /**
     * Creates new form PaginaAluno
     */
    public PaginaAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        header_icon = new javax.swing.JPanel();
        icon_label_maua = new javax.swing.JLabel();
        icone_min_max_close = new javax.swing.JPanel();
        button_min = new javax.swing.JPanel();
        max_panel = new javax.swing.JPanel();
        button_max = new javax.swing.JLabel();
        close_panel = new javax.swing.JPanel();
        button_sair = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(0, 0, 0));
        Header.setPreferredSize(new java.awt.Dimension(800, 50));
        Header.setLayout(new java.awt.BorderLayout());

        header_icon.setBackground(new java.awt.Color(0, 0, 0));
        header_icon.setPreferredSize(new java.awt.Dimension(200, 100));
        header_icon.setLayout(new java.awt.BorderLayout());

        icon_label_maua.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        icon_label_maua.setForeground(new java.awt.Color(255, 255, 255));
        icon_label_maua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_label_maua.setText("MAUÁ");
        header_icon.add(icon_label_maua, java.awt.BorderLayout.CENTER);

        Header.add(header_icon, java.awt.BorderLayout.LINE_START);

        icone_min_max_close.setBackground(new java.awt.Color(0, 0, 0));
        icone_min_max_close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_min.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout button_minLayout = new javax.swing.GroupLayout(button_min);
        button_min.setLayout(button_minLayout);
        button_minLayout.setHorizontalGroup(
            button_minLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        button_minLayout.setVerticalGroup(
            button_minLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        icone_min_max_close.add(button_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        max_panel.setBackground(new java.awt.Color(0, 0, 0));
        max_panel.setPreferredSize(new java.awt.Dimension(50, 50));
        max_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                max_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                max_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                max_panelMouseExited(evt);
            }
        });
        max_panel.setLayout(new java.awt.BorderLayout());

        button_max.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button_max.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/full_screen_32px.png"))); // NOI18N
        max_panel.add(button_max, java.awt.BorderLayout.CENTER);

        icone_min_max_close.add(max_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        close_panel.setBackground(new java.awt.Color(0, 0, 0));
        close_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close_panelMouseExited(evt);
            }
        });
        close_panel.setLayout(new java.awt.BorderLayout());

        button_sair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete_32px.png"))); // NOI18N
        close_panel.add(button_sair, java.awt.BorderLayout.CENTER);

        icone_min_max_close.add(close_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 50));

        Header.add(icone_min_max_close, java.awt.BorderLayout.LINE_END);

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 50, 450));

        jPanel2.setBackground(new java.awt.Color(73, 128, 242));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        jLabel1.setText("BEM-VINDO ,");

        jTextPane1.setBackground(new java.awt.Color(73, 128, 242));
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        jTextPane1.setText("NOME");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 450, 40));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        jLabel2.setText("ITENS PARA EMPRÉSTIMO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addContainerGap(569, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 900, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void max_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max_panelMouseClicked
        if(this.getExtendedState()!= PaginaInicial.MAXIMIZED_BOTH){
            this.setExtendedState(PaginaInicial.MAXIMIZED_BOTH);
        }

        else{
            this.setExtendedState(PaginaInicial.NORMAL);
        }
    }//GEN-LAST:event_max_panelMouseClicked
    public void  changecolor(JPanel hover , Color rand){
        hover.setBackground(rand);
    }
    private void max_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max_panelMouseEntered
        changecolor(max_panel, new Color(19,19,19));
    }//GEN-LAST:event_max_panelMouseEntered

    private void max_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max_panelMouseExited
        changecolor(max_panel,new Color (0,0,0));
    }//GEN-LAST:event_max_panelMouseExited

    private void close_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_panelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_close_panelMouseClicked

    private void close_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_panelMouseEntered
        changecolor(close_panel, new Color(19,19,19));
    }//GEN-LAST:event_close_panelMouseEntered

    private void close_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_panelMouseExited
        changecolor(close_panel,new Color (0,0,0));
    }//GEN-LAST:event_close_panelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel button_max;
    private javax.swing.JPanel button_min;
    private javax.swing.JLabel button_sair;
    private javax.swing.JPanel close_panel;
    private javax.swing.JPanel header_icon;
    private javax.swing.JLabel icon_label_maua;
    private javax.swing.JPanel icone_min_max_close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel max_panel;
    // End of variables declaration//GEN-END:variables
}
