/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lock.ca_projeto;
import lock.Database.ConnectionFactory;
import java.util.Map;
import java.awt.font.TextAttribute;
import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import lock.DAO.MateriaisDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pivis
 */
public class PaginaMateriais extends javax.swing.JFrame {

    /**
     * Creates new form PaginaAluno
     */
    public PaginaMateriais() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        Panel_criar.setVisible(false);
        Panel_atualizar.setVisible(false);
        Panel_deletar.setVisible(false);
        Label_aviso.setVisible(false);
        JTable1.getTableHeader().setFont(new Font("Microsoft Yahei UI Light",Font.PLAIN , 14));
        JTable1.getTableHeader().setOpaque(false);
        JTable1.getTableHeader().setBackground(new Color(0,0,0));
        JTable1.getTableHeader().setForeground(new Color(255,255,255));
        JTable1.setForeground(new Color(0,0,0));
        JTable1.setRowHeight(25);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        header_icon = new javax.swing.JPanel();
        icon_label_maua = new javax.swing.JLabel();
        icone_min_max_close = new javax.swing.JPanel();
        button_min = new javax.swing.JPanel();
        max_panel = new javax.swing.JPanel();
        button_max = new javax.swing.JLabel();
        close_panel = new javax.swing.JPanel();
        button_sair = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable1 = new javax.swing.JTable();
        Panel_button_sair = new javax.swing.JPanel();
        button_voltar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        button_voltar1 = new javax.swing.JLabel();
        Panel_criar = new javax.swing.JPanel();
        textfield_IDMaterial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textfield_NomeMaterial = new javax.swing.JTextField();
        textfield_Quantidade = new javax.swing.JTextField();
        Label_IDMaterial = new javax.swing.JLabel();
        Label_NomeMaterial = new javax.swing.JLabel();
        textfield_QuantidadeDisp = new javax.swing.JTextField();
        Label_Quantidade = new javax.swing.JLabel();
        Label_QuantidadeDisp = new javax.swing.JLabel();
        Panel_criar_voltar_material = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Panel_confirmar_criar_material = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Panel_atualizar = new javax.swing.JPanel();
        textfield_IDMaterial1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textfield_NomeMaterial1 = new javax.swing.JTextField();
        textfield_Quantidade1 = new javax.swing.JTextField();
        Label_IDMaterial1 = new javax.swing.JLabel();
        Label_NomeMaterial1 = new javax.swing.JLabel();
        textfield_QuantidadeDisp1 = new javax.swing.JTextField();
        Label_Quantidade1 = new javax.swing.JLabel();
        Label_QuantidadeDisp1 = new javax.swing.JLabel();
        Panel_voltar_atualizar_material = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Panel_confirmar_atualizar_material = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Panel_deletar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textfield_IDMaterial2 = new javax.swing.JTextField();
        Label_IDMaterial2 = new javax.swing.JLabel();
        textfield_IDMaterial3 = new javax.swing.JTextField();
        Label_IDMaterial3 = new javax.swing.JLabel();
        Label_aviso = new javax.swing.JLabel();
        Panel_voltar_deletar_material = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Panel_confirmar_deletar_material = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        panel_barra_menu = new javax.swing.JPanel();
        panel_hide_menu = new javax.swing.JPanel();
        button_hide_menu = new javax.swing.JLabel();
        Panel_Menu_Extendido = new javax.swing.JPanel();
        Panel_button_materiais = new javax.swing.JPanel();
        button_materiais = new javax.swing.JLabel();
        Panel_button_autorizacao = new javax.swing.JPanel();
        button_autorizacao = new javax.swing.JLabel();
        Panel_button_feedbacks = new javax.swing.JPanel();
        button_feedbacks = new javax.swing.JLabel();
        Panel_botoes_CRUD = new javax.swing.JPanel();
        Panel_button_criar = new javax.swing.JPanel();
        button_criar = new javax.swing.JLabel();
        Panel_button_atualizar = new javax.swing.JPanel();
        button_atualizar = new javax.swing.JLabel();
        Panel_button_deletar = new javax.swing.JPanel();
        button_deletar = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(0, 0, 0));
        Header.setPreferredSize(new java.awt.Dimension(800, 50));
        Header.setLayout(new java.awt.BorderLayout());

        header_icon.setBackground(new java.awt.Color(0, 0, 0));
        header_icon.setPreferredSize(new java.awt.Dimension(200, 100));
        header_icon.setLayout(new java.awt.BorderLayout());

        icon_label_maua.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 48)); // NOI18N
        icon_label_maua.setForeground(new java.awt.Color(255, 255, 255));
        icon_label_maua.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        icon_label_maua.setText("  LOCKC.A");
        header_icon.add(icon_label_maua, java.awt.BorderLayout.CENTER);

        Header.add(header_icon, java.awt.BorderLayout.LINE_START);

        icone_min_max_close.setBackground(new java.awt.Color(0, 0, 0));
        icone_min_max_close.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button_min.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout button_minLayout = new javax.swing.GroupLayout(button_min);
        button_min.setLayout(button_minLayout);
        button_minLayout.setHorizontalGroup(
            button_minLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        button_minLayout.setVerticalGroup(
            button_minLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        icone_min_max_close.add(button_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        max_panel.setBackground(new java.awt.Color(0, 0, 0));
        max_panel.setPreferredSize(new java.awt.Dimension(50, 50));
        max_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                max_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                max_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                max_panelMouseExited(evt);
            }
        });
        max_panel.setLayout(new java.awt.BorderLayout());

        button_max.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button_max.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/full_screen_32px.png"))); // NOI18N
        max_panel.add(button_max, java.awt.BorderLayout.CENTER);

        icone_min_max_close.add(max_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        close_panel.setBackground(new java.awt.Color(0, 0, 0));
        close_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close_panelMouseExited(evt);
            }
        });
        close_panel.setLayout(new java.awt.BorderLayout());

        button_sair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete_32px.png"))); // NOI18N
        close_panel.add(button_sair, java.awt.BorderLayout.CENTER);

        icone_min_max_close.add(close_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 50));

        Header.add(icone_min_max_close, java.awt.BorderLayout.LINE_END);

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        jPanel2.setBackground(new java.awt.Color(73, 128, 242));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(null);

        JTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JTable1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        JTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idMaterial", "Material", "Quantidade", "Disponibilidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JTable1.setFocusable(false);
        JTable1.setGridColor(new java.awt.Color(0, 0, 0));
        JTable1.setRowHeight(25);
        JTable1.setSelectionBackground(new java.awt.Color(83, 83, 83));
        JTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        JTable1.setShowGrid(false);
        JTable1.setShowHorizontalLines(true);
        JTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(JTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 550, 320));

        Panel_button_sair.setBackground(new java.awt.Color(73, 128, 242));
        Panel_button_sair.setLayout(new java.awt.BorderLayout());

        button_voltar.setBackground(new java.awt.Color(73, 128, 242));
        button_voltar.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        button_voltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button_voltar.setText("SAIR");
        button_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_voltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_voltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_voltarMouseExited(evt);
            }
        });
        Panel_button_sair.add(button_voltar, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(Panel_button_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 60, 30));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        jLabel1.setText("MATERIAIS DO CA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 160, 30));

        button_voltar1.setBackground(new java.awt.Color(73, 128, 242));
        button_voltar1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        button_voltar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button_voltar1.setText("SAIR");
        button_voltar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_voltar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_voltar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_voltar1MouseExited(evt);
            }
        });
        jPanel2.add(button_voltar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 60, -1));

        Panel_criar.setBackground(new java.awt.Color(0, 0, 0));

        textfield_IDMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_IDMaterialActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CRIAR MATERIAL");

        textfield_NomeMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_NomeMaterialActionPerformed(evt);
            }
        });

        Label_IDMaterial.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        Label_IDMaterial.setForeground(new java.awt.Color(255, 255, 255));
        Label_IDMaterial.setText("ID MATERIAL");

        Label_NomeMaterial.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        Label_NomeMaterial.setForeground(new java.awt.Color(255, 255, 255));
        Label_NomeMaterial.setText("NOME DO MATERIAL");

        Label_Quantidade.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        Label_Quantidade.setForeground(new java.awt.Color(255, 255, 255));
        Label_Quantidade.setText("QUANTIDADE");

        Label_QuantidadeDisp.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        Label_QuantidadeDisp.setForeground(new java.awt.Color(255, 255, 255));
        Label_QuantidadeDisp.setText("QUANTIDADE DISPONÍVEL");

        Panel_criar_voltar_material.setPreferredSize(new java.awt.Dimension(117, 31));
        Panel_criar_voltar_material.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_criar_voltar_materialMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_criar_voltar_materialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_criar_voltar_materialMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("VOLTAR");

        javax.swing.GroupLayout Panel_criar_voltar_materialLayout = new javax.swing.GroupLayout(Panel_criar_voltar_material);
        Panel_criar_voltar_material.setLayout(Panel_criar_voltar_materialLayout);
        Panel_criar_voltar_materialLayout.setHorizontalGroup(
            Panel_criar_voltar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );
        Panel_criar_voltar_materialLayout.setVerticalGroup(
            Panel_criar_voltar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        Panel_confirmar_criar_material.setPreferredSize(new java.awt.Dimension(117, 31));
        Panel_confirmar_criar_material.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_confirmar_criar_materialMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_confirmar_criar_materialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_confirmar_criar_materialMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CONFIRMAR");

        javax.swing.GroupLayout Panel_confirmar_criar_materialLayout = new javax.swing.GroupLayout(Panel_confirmar_criar_material);
        Panel_confirmar_criar_material.setLayout(Panel_confirmar_criar_materialLayout);
        Panel_confirmar_criar_materialLayout.setHorizontalGroup(
            Panel_confirmar_criar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );
        Panel_confirmar_criar_materialLayout.setVerticalGroup(
            Panel_confirmar_criar_materialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Panel_criarLayout = new javax.swing.GroupLayout(Panel_criar);
        Panel_criar.setLayout(Panel_criarLayout);
        Panel_criarLayout.setHorizontalGroup(
            Panel_criarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_criarLayout.createSequentialGroup()
                .addGroup(Panel_criarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_criarLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel2))
                    .addGroup(Panel_criarLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(Panel_criarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_criarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_criarLayout.createSequentialGroup()
                                    .addComponent(Panel_criar_voltar_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Panel_confirmar_criar_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(textfield_NomeMaterial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                .addComponent(textfield_IDMaterial, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textfield_Quantidade, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Label_NomeMaterial, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textfield_QuantidadeDisp, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Label_IDMaterial, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Label_QuantidadeDisp, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        Panel_criarLayout.setVerticalGroup(
            Panel_criarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_criarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(Label_IDMaterial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_IDMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(Label_NomeMaterial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_NomeMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_QuantidadeDisp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_QuantidadeDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Panel_criarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_criarLayout.createSequentialGroup()
                        .addComponent(Panel_criar_voltar_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(Panel_criarLayout.createSequentialGroup()
                        .addComponent(Panel_confirmar_criar_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))))
        );

        jPanel2.add(Panel_criar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 550, 320));

        Panel_atualizar.setBackground(new java.awt.Color(0, 0, 0));

        textfield_IDMaterial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_IDMaterial1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ATUALIZAR  MATERIAL");

        textfield_NomeMaterial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_NomeMaterial1ActionPerformed(evt);
            }
        });

        Label_IDMaterial1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        Label_IDMaterial1.setForeground(new java.awt.Color(255, 255, 255));
        Label_IDMaterial1.setText("ID MATERIAL");

        Label_NomeMaterial1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        Label_NomeMaterial1.setForeground(new java.awt.Color(255, 255, 255));
        Label_NomeMaterial1.setText("NOME DO MATERIAL");

        Label_Quantidade1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        Label_Quantidade1.setForeground(new java.awt.Color(255, 255, 255));
        Label_Quantidade1.setText("QUANTIDADE");

        Label_QuantidadeDisp1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        Label_QuantidadeDisp1.setForeground(new java.awt.Color(255, 255, 255));
        Label_QuantidadeDisp1.setText("QUANTIDADE DISPONÍVEL");

        Panel_voltar_atualizar_material.setPreferredSize(new java.awt.Dimension(117, 31));
        Panel_voltar_atualizar_material.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_voltar_atualizar_materialMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_voltar_atualizar_materialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_voltar_atualizar_materialMouseExited(evt);
            }
        });
        Panel_voltar_atualizar_material.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("VOLTAR");
        Panel_voltar_atualizar_material.add(jLabel7, java.awt.BorderLayout.CENTER);

        Panel_confirmar_atualizar_material.setPreferredSize(new java.awt.Dimension(117, 31));
        Panel_confirmar_atualizar_material.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_confirmar_atualizar_materialMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_confirmar_atualizar_materialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_confirmar_atualizar_materialMouseExited(evt);
            }
        });
        Panel_confirmar_atualizar_material.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CONFIRMAR");
        Panel_confirmar_atualizar_material.add(jLabel8, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout Panel_atualizarLayout = new javax.swing.GroupLayout(Panel_atualizar);
        Panel_atualizar.setLayout(Panel_atualizarLayout);
        Panel_atualizarLayout.setHorizontalGroup(
            Panel_atualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_atualizarLayout.createSequentialGroup()
                .addGroup(Panel_atualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_atualizarLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel3))
                    .addGroup(Panel_atualizarLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(Panel_atualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Quantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_atualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_atualizarLayout.createSequentialGroup()
                                    .addComponent(Panel_voltar_atualizar_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Panel_confirmar_atualizar_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(textfield_NomeMaterial1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                .addComponent(textfield_IDMaterial1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textfield_Quantidade1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Label_NomeMaterial1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textfield_QuantidadeDisp1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Label_IDMaterial1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Label_QuantidadeDisp1, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGap(32, 148, Short.MAX_VALUE))
        );
        Panel_atualizarLayout.setVerticalGroup(
            Panel_atualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_atualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_IDMaterial1)
                .addGap(5, 5, 5)
                .addComponent(textfield_IDMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_NomeMaterial1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfield_NomeMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_atualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_atualizarLayout.createSequentialGroup()
                        .addComponent(Label_Quantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfield_Quantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_QuantidadeDisp1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfield_QuantidadeDisp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(Panel_voltar_atualizar_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_atualizarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Panel_confirmar_atualizar_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        jPanel2.add(Panel_atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 550, 320));

        Panel_deletar.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DELETAR MATERIAL");

        textfield_IDMaterial2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_IDMaterial2ActionPerformed(evt);
            }
        });

        Label_IDMaterial2.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        Label_IDMaterial2.setForeground(new java.awt.Color(255, 255, 255));
        Label_IDMaterial2.setText("ID MATERIAL");

        textfield_IDMaterial3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_IDMaterial3ActionPerformed(evt);
            }
        });

        Label_IDMaterial3.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        Label_IDMaterial3.setForeground(new java.awt.Color(255, 255, 255));
        Label_IDMaterial3.setText("ID MATERIAL NOVAMENTE");

        Label_aviso.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        Label_aviso.setForeground(new java.awt.Color(255, 0, 0));
        Label_aviso.setText("IDs DIFERENTES , CUIDADO ESSA AÇÃO É IRREVERSÍVEL");

        Panel_voltar_deletar_material.setPreferredSize(new java.awt.Dimension(117, 31));
        Panel_voltar_deletar_material.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_voltar_deletar_materialMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_voltar_deletar_materialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_voltar_deletar_materialMouseExited(evt);
            }
        });
        Panel_voltar_deletar_material.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("VOLTAR");
        Panel_voltar_deletar_material.add(jLabel9, java.awt.BorderLayout.CENTER);

        Panel_confirmar_deletar_material.setPreferredSize(new java.awt.Dimension(117, 31));
        Panel_confirmar_deletar_material.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_confirmar_deletar_materialMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_confirmar_deletar_materialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_confirmar_deletar_materialMouseExited(evt);
            }
        });
        Panel_confirmar_deletar_material.setLayout(new java.awt.BorderLayout());

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CONFIRMAR");
        Panel_confirmar_deletar_material.add(jLabel10, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout Panel_deletarLayout = new javax.swing.GroupLayout(Panel_deletar);
        Panel_deletar.setLayout(Panel_deletarLayout);
        Panel_deletarLayout.setHorizontalGroup(
            Panel_deletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_deletarLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Panel_deletarLayout.createSequentialGroup()
                .addGroup(Panel_deletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_deletarLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(Panel_deletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_IDMaterial2)
                            .addComponent(Label_IDMaterial3)
                            .addGroup(Panel_deletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_deletarLayout.createSequentialGroup()
                                    .addComponent(Panel_voltar_deletar_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Panel_confirmar_deletar_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(textfield_IDMaterial2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                .addComponent(textfield_IDMaterial3, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(Panel_deletarLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(Label_aviso)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        Panel_deletarLayout.setVerticalGroup(
            Panel_deletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_deletarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(Label_IDMaterial2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textfield_IDMaterial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Label_IDMaterial3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textfield_IDMaterial3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(Panel_deletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_deletarLayout.createSequentialGroup()
                        .addComponent(Panel_voltar_deletar_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Label_aviso))
                    .addComponent(Panel_confirmar_deletar_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.add(Panel_deletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 550, 320));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 740, 450));

        panel_barra_menu.setBackground(new java.awt.Color(0, 0, 0));

        panel_hide_menu.setBackground(new java.awt.Color(0, 0, 0));
        panel_hide_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_hide_menuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_hide_menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_hide_menuMouseExited(evt);
            }
        });
        panel_hide_menu.setLayout(new java.awt.BorderLayout());

        button_hide_menu.setBackground(new java.awt.Color(0, 0, 0));
        button_hide_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/left_arrow_icon.png"))); // NOI18N
        panel_hide_menu.add(button_hide_menu, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout panel_barra_menuLayout = new javax.swing.GroupLayout(panel_barra_menu);
        panel_barra_menu.setLayout(panel_barra_menuLayout);
        panel_barra_menuLayout.setHorizontalGroup(
            panel_barra_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_barra_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_hide_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_barra_menuLayout.setVerticalGroup(
            panel_barra_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_barra_menuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panel_hide_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel_barra_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 50, 450));

        Panel_Menu_Extendido.setBackground(new java.awt.Color(0, 0, 0));
        Panel_Menu_Extendido.setPreferredSize(new java.awt.Dimension(160, 360));

        Panel_button_materiais.setBackground(new java.awt.Color(200, 200, 200));
        Panel_button_materiais.setPreferredSize(new java.awt.Dimension(135, 60));
        Panel_button_materiais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_button_materiaisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_button_materiaisMouseExited(evt);
            }
        });

        button_materiais.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        button_materiais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button_materiais.setText("Materiais");
        button_materiais.setPreferredSize(new java.awt.Dimension(60, 135));

        javax.swing.GroupLayout Panel_button_materiaisLayout = new javax.swing.GroupLayout(Panel_button_materiais);
        Panel_button_materiais.setLayout(Panel_button_materiaisLayout);
        Panel_button_materiaisLayout.setHorizontalGroup(
            Panel_button_materiaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_materiais, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        Panel_button_materiaisLayout.setVerticalGroup(
            Panel_button_materiaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_materiais, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        Panel_button_autorizacao.setBackground(new java.awt.Color(230, 230, 230));
        Panel_button_autorizacao.setPreferredSize(new java.awt.Dimension(135, 60));
        Panel_button_autorizacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_button_autorizacaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_button_autorizacaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_button_autorizacaoMouseExited(evt);
            }
        });

        button_autorizacao.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        button_autorizacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button_autorizacao.setText("Empréstimo");

        javax.swing.GroupLayout Panel_button_autorizacaoLayout = new javax.swing.GroupLayout(Panel_button_autorizacao);
        Panel_button_autorizacao.setLayout(Panel_button_autorizacaoLayout);
        Panel_button_autorizacaoLayout.setHorizontalGroup(
            Panel_button_autorizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_autorizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        Panel_button_autorizacaoLayout.setVerticalGroup(
            Panel_button_autorizacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_autorizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Panel_button_feedbacks.setBackground(new java.awt.Color(230, 230, 230));
        Panel_button_feedbacks.setPreferredSize(new java.awt.Dimension(135, 60));
        Panel_button_feedbacks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_button_feedbacksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_button_feedbacksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_button_feedbacksMouseExited(evt);
            }
        });
        Panel_button_feedbacks.setLayout(new java.awt.BorderLayout());

        button_feedbacks.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        button_feedbacks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button_feedbacks.setText("Feedback");
        Panel_button_feedbacks.add(button_feedbacks, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout Panel_Menu_ExtendidoLayout = new javax.swing.GroupLayout(Panel_Menu_Extendido);
        Panel_Menu_Extendido.setLayout(Panel_Menu_ExtendidoLayout);
        Panel_Menu_ExtendidoLayout.setHorizontalGroup(
            Panel_Menu_ExtendidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_button_materiais, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Panel_button_autorizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Panel_button_feedbacks, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        Panel_Menu_ExtendidoLayout.setVerticalGroup(
            Panel_Menu_ExtendidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Menu_ExtendidoLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(Panel_button_materiais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Panel_button_autorizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Panel_button_feedbacks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(Panel_Menu_Extendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 450));

        Panel_botoes_CRUD.setBackground(new java.awt.Color(0, 0, 0));
        Panel_botoes_CRUD.setPreferredSize(new java.awt.Dimension(160, 360));

        Panel_button_criar.setBackground(new java.awt.Color(230, 230, 230));
        Panel_button_criar.setPreferredSize(new java.awt.Dimension(135, 60));
        Panel_button_criar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_button_criarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_button_criarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_button_criarMouseExited(evt);
            }
        });

        button_criar.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        button_criar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button_criar.setText("Criar");
        button_criar.setPreferredSize(new java.awt.Dimension(60, 135));

        javax.swing.GroupLayout Panel_button_criarLayout = new javax.swing.GroupLayout(Panel_button_criar);
        Panel_button_criar.setLayout(Panel_button_criarLayout);
        Panel_button_criarLayout.setHorizontalGroup(
            Panel_button_criarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_criar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        Panel_button_criarLayout.setVerticalGroup(
            Panel_button_criarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_criar, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        Panel_button_atualizar.setBackground(new java.awt.Color(230, 230, 230));
        Panel_button_atualizar.setPreferredSize(new java.awt.Dimension(135, 60));
        Panel_button_atualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_button_atualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_button_atualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_button_atualizarMouseExited(evt);
            }
        });

        button_atualizar.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        button_atualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button_atualizar.setText("Atualizar");

        javax.swing.GroupLayout Panel_button_atualizarLayout = new javax.swing.GroupLayout(Panel_button_atualizar);
        Panel_button_atualizar.setLayout(Panel_button_atualizarLayout);
        Panel_button_atualizarLayout.setHorizontalGroup(
            Panel_button_atualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        Panel_button_atualizarLayout.setVerticalGroup(
            Panel_button_atualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Panel_button_deletar.setBackground(new java.awt.Color(230, 230, 230));
        Panel_button_deletar.setPreferredSize(new java.awt.Dimension(135, 60));
        Panel_button_deletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_button_deletarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_button_deletarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_button_deletarMouseExited(evt);
            }
        });

        button_deletar.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        button_deletar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button_deletar.setText("Deletar");

        javax.swing.GroupLayout Panel_button_deletarLayout = new javax.swing.GroupLayout(Panel_button_deletar);
        Panel_button_deletar.setLayout(Panel_button_deletarLayout);
        Panel_button_deletarLayout.setHorizontalGroup(
            Panel_button_deletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        Panel_button_deletarLayout.setVerticalGroup(
            Panel_button_deletarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout Panel_botoes_CRUDLayout = new javax.swing.GroupLayout(Panel_botoes_CRUD);
        Panel_botoes_CRUD.setLayout(Panel_botoes_CRUDLayout);
        Panel_botoes_CRUDLayout.setHorizontalGroup(
            Panel_botoes_CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_button_criar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Panel_button_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Panel_button_deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        Panel_botoes_CRUDLayout.setVerticalGroup(
            Panel_botoes_CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_botoes_CRUDLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(Panel_button_criar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Panel_button_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Panel_button_deletar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(Panel_botoes_CRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    boolean a = true;
    private void max_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max_panelMouseClicked
        if (this.getExtendedState() != PaginaMateriais.MAXIMIZED_BOTH) {
            this.setExtendedState(PaginaMateriais.MAXIMIZED_BOTH);
        } else {
            this.setExtendedState(PaginaMateriais.NORMAL);
        }
    }//GEN-LAST:event_max_panelMouseClicked
    public void changecolor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }
    public void clickmenu(JPanel h1,int numberbool){
        
    }
    public void hideshow(JPanel menushowhide,boolean dashboard){
      if (dashboard == true){  
         Panel_Menu_Extendido.setPreferredSize(new Dimension(0, Panel_Menu_Extendido.getHeight()));
         Panel_button_materiais.setVisible(false);
         Panel_button_autorizacao.setVisible(false);
         Panel_button_feedbacks.setVisible(false);
         Panel_botoes_CRUD.setPreferredSize(new Dimension(160, Panel_botoes_CRUD.getHeight()));
         Panel_button_atualizar.setVisible(true);
         Panel_button_criar.setVisible(true);
         Panel_button_deletar.setVisible(true);
         //int x , int y , width , height
         jScrollPane1.setBounds(540,320,460,400);
         changeimage(button_hide_menu,"/icons/right_arrow_icon.png");
      }
      else{
         Panel_Menu_Extendido.setPreferredSize(new Dimension(160, Panel_Menu_Extendido.getHeight()));
         Panel_button_materiais.setVisible(true);
         Panel_button_autorizacao.setVisible(true);
         Panel_button_feedbacks.setVisible(true);
         Panel_botoes_CRUD.setPreferredSize(new Dimension(0, Panel_botoes_CRUD.getHeight()));
         Panel_button_atualizar.setVisible(false);
         Panel_button_criar.setVisible(false);
         Panel_button_deletar.setVisible(false);
         changeimage(button_hide_menu,"/icons/left_arrow_icon.png");
      }  jScrollPane1.setBounds(540,320,460,400);
    }
    private void max_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max_panelMouseEntered
        changecolor(max_panel, new Color(19, 19, 19));
    }//GEN-LAST:event_max_panelMouseEntered

    private void max_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_max_panelMouseExited
        changecolor(max_panel, new Color(0, 0, 0));
    }//GEN-LAST:event_max_panelMouseExited

    private void close_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_panelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_close_panelMouseClicked

    private void close_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_panelMouseEntered
        changecolor(close_panel, new Color(19, 19, 19));
    }//GEN-LAST:event_close_panelMouseEntered

    private void close_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_panelMouseExited
        changecolor(close_panel, new Color(0, 0, 0));
    }//GEN-LAST:event_close_panelMouseExited

    private void panel_hide_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_hide_menuMouseClicked
         clickmenu(panel_hide_menu,1);
         if(a == true){
            hideshow(Panel_Menu_Extendido,a);
            SwingUtilities.updateComponentTreeUI(this);
            a = false;
         }
         else{
             hideshow(Panel_Menu_Extendido,a);
             SwingUtilities.updateComponentTreeUI(this);
             a = true;
         }
    }//GEN-LAST:event_panel_hide_menuMouseClicked

    private void panel_hide_menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_hide_menuMouseEntered
    
    }//GEN-LAST:event_panel_hide_menuMouseEntered

    private void panel_hide_menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_hide_menuMouseExited

    }//GEN-LAST:event_panel_hide_menuMouseExited

    private void button_voltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_voltarMouseEntered
        Font originalFont = button_voltar.getFont();
        Map attributes = originalFont.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        button_voltar.setFont(originalFont.deriveFont(attributes));
    }//GEN-LAST:event_button_voltarMouseEntered

    private void button_voltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_voltarMouseExited
        Font originalFont = button_voltar.getFont();
        Map attributes = originalFont.getAttributes();
        attributes.put(TextAttribute.UNDERLINE,-1);
        button_voltar.setFont(originalFont.deriveFont(attributes));
    }//GEN-LAST:event_button_voltarMouseExited

    private void button_voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_voltarMouseClicked
         PaginaLogin mi = new PaginaLogin();
                mi.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_button_voltarMouseClicked

    private void Panel_button_materiaisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_button_materiaisMouseEntered
        Font originalFont = button_materiais.getFont();
        Map attributes = originalFont.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        button_materiais.setFont(originalFont.deriveFont(attributes));
    }//GEN-LAST:event_Panel_button_materiaisMouseEntered

    private void Panel_button_materiaisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_button_materiaisMouseExited
        Font originalFont = button_materiais.getFont();
        Map attributes = originalFont.getAttributes();
        attributes.put(TextAttribute.UNDERLINE,-1);
        button_materiais.setFont(originalFont.deriveFont(attributes));
    }//GEN-LAST:event_Panel_button_materiaisMouseExited

    private void Panel_button_autorizacaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_button_autorizacaoMouseEntered
        Font originalFont = button_autorizacao.getFont();
        Map attributes = originalFont.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        button_autorizacao.setFont(originalFont.deriveFont(attributes));
        changecolor(Panel_button_autorizacao, new Color(200,200,200));
    }//GEN-LAST:event_Panel_button_autorizacaoMouseEntered

    private void Panel_button_autorizacaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_button_autorizacaoMouseExited
        Font originalFont = button_autorizacao.getFont();
        Map attributes = originalFont.getAttributes();
        attributes.put(TextAttribute.UNDERLINE,-1);
        button_autorizacao.setFont(originalFont.deriveFont(attributes));
        changecolor(Panel_button_autorizacao, new Color(242,242,242));
    }//GEN-LAST:event_Panel_button_autorizacaoMouseExited

    private void Panel_button_autorizacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_button_autorizacaoMouseClicked
        PaginaValidar PV = new PaginaValidar();
        PV.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Panel_button_autorizacaoMouseClicked

    private void Panel_button_feedbacksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_button_feedbacksMouseEntered
        Font originalFont = button_feedbacks.getFont();
        Map attributes = originalFont.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        button_feedbacks.setFont(originalFont.deriveFont(attributes));
        changecolor(Panel_button_feedbacks, new Color(200,200,200));
    }//GEN-LAST:event_Panel_button_feedbacksMouseEntered

    private void Panel_button_feedbacksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_button_feedbacksMouseExited
        Font originalFont = button_feedbacks.getFont();
        Map attributes = originalFont.getAttributes();
        attributes.put(TextAttribute.UNDERLINE,-1);
        button_feedbacks.setFont(originalFont.deriveFont(attributes));
        changecolor(Panel_button_feedbacks, new Color(242,242,242));
    }//GEN-LAST:event_Panel_button_feedbacksMouseExited

    private void Panel_button_feedbacksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_button_feedbacksMouseClicked
        PaginaFeedback PF = new PaginaFeedback();
        PF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Panel_button_feedbacksMouseClicked

    private void Panel_button_criarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_button_criarMouseEntered
         changecolor(Panel_button_criar, new Color(200,200,200));
    }//GEN-LAST:event_Panel_button_criarMouseEntered

    private void Panel_button_criarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_button_criarMouseExited
         changecolor(Panel_button_criar, new Color(242,242,242));
    }//GEN-LAST:event_Panel_button_criarMouseExited

    private void Panel_button_atualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_button_atualizarMouseClicked
        jScrollPane1.setVisible(false);
        jLabel1.setVisible(false);
        Panel_criar.setVisible(false);
        Panel_deletar.setVisible(false);
        Panel_atualizar.setVisible(true);
        Panel_voltar_atualizar_material.setVisible(true);
        changecolor(Panel_button_atualizar, new Color(200,200,200));
    }//GEN-LAST:event_Panel_button_atualizarMouseClicked

    private void Panel_button_atualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_button_atualizarMouseEntered
        changecolor(Panel_button_atualizar, new Color(200,200,200));
    }//GEN-LAST:event_Panel_button_atualizarMouseEntered

    private void Panel_button_atualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_button_atualizarMouseExited
        changecolor(Panel_button_atualizar, new Color(242,242,242));
    }//GEN-LAST:event_Panel_button_atualizarMouseExited

    private void Panel_button_deletarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_button_deletarMouseClicked
        Panel_voltar_deletar_material.setVisible(true);
        jScrollPane1.setVisible(false);
        jLabel1.setVisible(false);
        Panel_criar.setVisible(false);
        Panel_atualizar.setVisible(false);
        Panel_deletar.setVisible(true);
        changecolor(Panel_button_deletar, new Color(200,200,200));
    }//GEN-LAST:event_Panel_button_deletarMouseClicked

    private void Panel_button_deletarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_button_deletarMouseEntered
        changecolor(Panel_button_deletar, new Color(200,200,200));
    }//GEN-LAST:event_Panel_button_deletarMouseEntered

    private void Panel_button_deletarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_button_deletarMouseExited
        changecolor(Panel_button_deletar, new Color(242,242,242));
    }//GEN-LAST:event_Panel_button_deletarMouseExited

    private void button_voltar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_voltar1MouseClicked
        PaginaLogin mi = new PaginaLogin();
        mi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_voltar1MouseClicked

    private void button_voltar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_voltar1MouseEntered
        Font originalFont = button_voltar.getFont();
        Map attributes = originalFont.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        button_voltar.setFont(originalFont.deriveFont(attributes));
    }//GEN-LAST:event_button_voltar1MouseEntered

    private void button_voltar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_voltar1MouseExited
        Font originalFont = button_voltar.getFont();
        Map attributes = originalFont.getAttributes();
        attributes.put(TextAttribute.UNDERLINE,-1);
        button_voltar.setFont(originalFont.deriveFont(attributes));
    }//GEN-LAST:event_button_voltar1MouseExited

    private void Panel_button_criarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_button_criarMouseClicked
        jScrollPane1.setVisible(false);
        jLabel1.setVisible(false);
        Panel_atualizar.setVisible(false);
        Panel_deletar.setVisible(false);
        Panel_criar.setVisible(true);
        changecolor(Panel_button_criar, new Color(200,200,200));
    }//GEN-LAST:event_Panel_button_criarMouseClicked

    private void textfield_IDMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_IDMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_IDMaterialActionPerformed

    private void textfield_NomeMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_NomeMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_NomeMaterialActionPerformed

    private void textfield_IDMaterial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_IDMaterial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_IDMaterial1ActionPerformed

    private void textfield_NomeMaterial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_NomeMaterial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_NomeMaterial1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            //insira sua senha no "senha"
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbcalok","root","Bobvisoto17");
            Statement st = conn.createStatement();
            String sql = "select * from material";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                String idMaterial = String.valueOf(rs.getInt("idMaterial"));
                String material = rs.getString("material");
                String quantidade = String.valueOf(rs.getInt("quantidadeTotal"));
                String disponibilidade = String.valueOf(rs.getInt("quantidadeDisponivel"));
                String materialData[] = {idMaterial,material,quantidade,disponibilidade};
                    DefaultTableModel materialModel = (DefaultTableModel)JTable1.getModel();
                    materialModel.addRow(materialData); 
            }
        conn.close();
        }
        catch(Exception e){
            System.out.println(e.getMessage());
    }
    }//GEN-LAST:event_formWindowOpened

    private void textfield_IDMaterial2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_IDMaterial2ActionPerformed
        try{
            //insira sua senha no "senha"
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbcalok","root","Bobvisoto17");
            Statement st = conn.createStatement();
            String sql = "select * from material";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                String idMaterial = String.valueOf(rs.getInt("idMaterial"));
                String material = rs.getString("material");
                String quantidade = String.valueOf(rs.getInt("quantidadeTotal"));
                String disponibilidade = String.valueOf(rs.getInt("quantidadeDisponivel"));
                String materialData[] = {idMaterial,material,quantidade,disponibilidade};
                    DefaultTableModel materialModel = (DefaultTableModel)JTable1.getModel();
                    materialModel.addRow(materialData); 
            }
        conn.close();
        }
        catch(Exception e){
            System.out.println(e.getMessage());
    }
    }//GEN-LAST:event_textfield_IDMaterial2ActionPerformed

    private void textfield_IDMaterial3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_IDMaterial3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_IDMaterial3ActionPerformed

    private void Panel_criar_voltar_materialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_criar_voltar_materialMouseClicked
         jScrollPane1.setVisible(true);
        jLabel1.setVisible(true);
        Panel_criar.setVisible(false);
        changecolor(Panel_button_criar,new Color(242,242,242));
        DefaultTableModel materialreset = (DefaultTableModel) JTable1.getModel();
        materialreset.setRowCount(0);
        try{
            //insira sua senha no "senha"
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbcalok","root","Bobvisoto17");
            Statement st = conn.createStatement();
            String sql = "select * from material";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                String idMaterial = String.valueOf(rs.getInt("idMaterial"));
                String material = rs.getString("material");
                String quantidade = String.valueOf(rs.getInt("quantidadeTotal"));
                String disponibilidade = String.valueOf(rs.getInt("quantidadeDisponivel"));
                String materialData[] = {idMaterial,material,quantidade,disponibilidade};
                    DefaultTableModel materialModel = (DefaultTableModel)JTable1.getModel();
                    materialModel.addRow(materialData); 
            }
        conn.close();
        }
        catch(Exception e){
            System.out.println(e.getMessage());
    }
    }//GEN-LAST:event_Panel_criar_voltar_materialMouseClicked

    private void Panel_criar_voltar_materialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_criar_voltar_materialMouseEntered
         changecolor(Panel_criar_voltar_material,new Color(200,200,200));
    }//GEN-LAST:event_Panel_criar_voltar_materialMouseEntered

    private void Panel_criar_voltar_materialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_criar_voltar_materialMouseExited
        changecolor(Panel_criar_voltar_material,new Color(242,242,242));
    }//GEN-LAST:event_Panel_criar_voltar_materialMouseExited

    private void Panel_confirmar_criar_materialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_confirmar_criar_materialMouseClicked
        String idMaterial = textfield_IDMaterial.getText();
        String material = textfield_NomeMaterial.getText();
        String quantidade = textfield_Quantidade.getText();
        String quantidade_disp = textfield_QuantidadeDisp.getText();
        try{    
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbcalok","root","Bobvisoto17");
            Statement st = conn.createStatement();
            String sql = "insert into material (idMaterial,material,quantidadeTotal,quantidadeDisponivel)values (?,?,?,?)";
            PreparedStatement prst = conn.prepareStatement(sql);
            prst.setString(1,idMaterial);
            prst.setString(2,material);
            prst.setString(3,quantidade);
            prst.setString(4,quantidade_disp);
            prst.execute();
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_Panel_confirmar_criar_materialMouseClicked

    private void Panel_confirmar_criar_materialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_confirmar_criar_materialMouseEntered
        changecolor(Panel_confirmar_criar_material,new Color(200,200,200));
    }//GEN-LAST:event_Panel_confirmar_criar_materialMouseEntered

    private void Panel_confirmar_criar_materialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_confirmar_criar_materialMouseExited
        changecolor(Panel_confirmar_criar_material,new Color(242,242,242));
    }//GEN-LAST:event_Panel_confirmar_criar_materialMouseExited

    private void Panel_voltar_atualizar_materialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_voltar_atualizar_materialMouseClicked
        jScrollPane1.setVisible(true);
        jLabel1.setVisible(true);
        Panel_criar.setVisible(false);
        Panel_voltar_atualizar_material.setVisible(false);
        DefaultTableModel materialreset = (DefaultTableModel) JTable1.getModel();
        materialreset.setRowCount(0);
        try{
            //insira sua senha no "senha"
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbcalok","root","Bobvisoto17");
            Statement st = conn.createStatement();
            String sql = "select * from material";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                String idMaterial = String.valueOf(rs.getInt("idMaterial"));
                String material = rs.getString("material");
                String quantidade = String.valueOf(rs.getInt("quantidadeTotal"));
                String disponibilidade = String.valueOf(rs.getInt("quantidadeDisponivel"));
                String materialData[] = {idMaterial,material,quantidade,disponibilidade};
                    DefaultTableModel materialModel = (DefaultTableModel)JTable1.getModel();
                    materialModel.addRow(materialData); 
            }
        conn.close();
        }
        catch(Exception e){
            System.out.println(e.getMessage());
    }
    }//GEN-LAST:event_Panel_voltar_atualizar_materialMouseClicked

    private void Panel_voltar_atualizar_materialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_voltar_atualizar_materialMouseEntered
        changecolor(Panel_voltar_atualizar_material ,new Color(200,200,200));
    }//GEN-LAST:event_Panel_voltar_atualizar_materialMouseEntered

    private void Panel_voltar_atualizar_materialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_voltar_atualizar_materialMouseExited
        changecolor(Panel_voltar_atualizar_material,new Color(242,242,242));
    }//GEN-LAST:event_Panel_voltar_atualizar_materialMouseExited

    private void Panel_confirmar_atualizar_materialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_confirmar_atualizar_materialMouseClicked
        String idMaterial = textfield_IDMaterial1.getText();
        String material = textfield_NomeMaterial1.getText();
        String quantidade = textfield_Quantidade1.getText();
        String quantidade_disp = textfield_QuantidadeDisp1.getText();
         try{    
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbcalok","root","Bobvisoto17");
            Statement st = conn.createStatement();
            String sql = "UPDATE material SET material=?,quantidadeTotal=?,quantidadeDisponivel=?  where idMaterial=?";
            PreparedStatement prst = conn.prepareStatement(sql);
            prst.setString(1,material);
            prst.setString(2,quantidade);
            prst.setString(3,quantidade_disp);
            prst.setString(4,idMaterial);
            prst.executeUpdate();
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_Panel_confirmar_atualizar_materialMouseClicked

    private void Panel_confirmar_atualizar_materialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_confirmar_atualizar_materialMouseEntered
        changecolor(Panel_confirmar_atualizar_material,new Color(200,200,200));
    }//GEN-LAST:event_Panel_confirmar_atualizar_materialMouseEntered

    private void Panel_confirmar_atualizar_materialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_confirmar_atualizar_materialMouseExited
        changecolor(Panel_confirmar_atualizar_material,new Color(242,242,242));
    }//GEN-LAST:event_Panel_confirmar_atualizar_materialMouseExited

    private void Panel_voltar_deletar_materialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_voltar_deletar_materialMouseClicked
        jScrollPane1.setVisible(true);
        jLabel1.setVisible(true);
        Panel_criar.setVisible(false);
        Panel_voltar_deletar_material.setVisible(false);
        DefaultTableModel materialreset = (DefaultTableModel) JTable1.getModel();
        materialreset.setRowCount(0);
        try{
            //insira sua senha no "senha"
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbcalok","root","Bobvisoto17");
            Statement st = conn.createStatement();
            String sql = "select * from material";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                String idMaterial = String.valueOf(rs.getInt("idMaterial"));
                String material = rs.getString("material");
                String quantidade = String.valueOf(rs.getInt("quantidadeTotal"));
                String disponibilidade = String.valueOf(rs.getInt("quantidadeDisponivel"));
                String materialData[] = {idMaterial,material,quantidade,disponibilidade};
                    DefaultTableModel materialModel = (DefaultTableModel)JTable1.getModel();
                    materialModel.addRow(materialData); 
            }
        conn.close();
        }
        catch(Exception e){
            System.out.println(e.getMessage());
    }
    }//GEN-LAST:event_Panel_voltar_deletar_materialMouseClicked

    private void Panel_voltar_deletar_materialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_voltar_deletar_materialMouseEntered
        changecolor(Panel_voltar_deletar_material,new Color(200,200,200));
    }//GEN-LAST:event_Panel_voltar_deletar_materialMouseEntered

    private void Panel_voltar_deletar_materialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_voltar_deletar_materialMouseExited
        changecolor(Panel_voltar_deletar_material,new Color(242,242,242));
    }//GEN-LAST:event_Panel_voltar_deletar_materialMouseExited

    private void Panel_confirmar_deletar_materialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_confirmar_deletar_materialMouseClicked
    String id = textfield_IDMaterial2.getText();
    String id2 = textfield_IDMaterial3.getText();
    if(id2.equals(id)){
        try{    
            Label_aviso.setVisible(false);
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbcalok","root","Bobvisoto17");
            Statement st = conn.createStatement();
            String sql = "DELETE FROM material WHERE idMaterial = ?";
            PreparedStatement prst = conn.prepareStatement(sql);
            prst.setString(1,id);
            prst.execute();
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    else{
        Label_aviso.setVisible(true);
    }
    }//GEN-LAST:event_Panel_confirmar_deletar_materialMouseClicked

    private void Panel_confirmar_deletar_materialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_confirmar_deletar_materialMouseEntered
        changecolor(Panel_confirmar_deletar_material,new Color(200,200,200));
    }//GEN-LAST:event_Panel_confirmar_deletar_materialMouseEntered

    private void Panel_confirmar_deletar_materialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_confirmar_deletar_materialMouseExited
        changecolor(Panel_confirmar_deletar_material,new Color(242,242,242));
    }//GEN-LAST:event_Panel_confirmar_deletar_materialMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaMateriais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaMateriais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaMateriais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaMateriais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaMateriais().setVisible(true);
            }
        });
    }
    public void changeimage(JLabel button, String resourcheimg){
       ImageIcon aimg = new ImageIcon(getClass().getResource(resourcheimg));
       button.setIcon(aimg);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    public javax.swing.JTable JTable1;
    private javax.swing.JLabel Label_IDMaterial;
    private javax.swing.JLabel Label_IDMaterial1;
    private javax.swing.JLabel Label_IDMaterial2;
    private javax.swing.JLabel Label_IDMaterial3;
    private javax.swing.JLabel Label_NomeMaterial;
    private javax.swing.JLabel Label_NomeMaterial1;
    private javax.swing.JLabel Label_Quantidade;
    private javax.swing.JLabel Label_Quantidade1;
    private javax.swing.JLabel Label_QuantidadeDisp;
    private javax.swing.JLabel Label_QuantidadeDisp1;
    private javax.swing.JLabel Label_aviso;
    private javax.swing.JPanel Panel_Menu_Extendido;
    private javax.swing.JPanel Panel_atualizar;
    private javax.swing.JPanel Panel_botoes_CRUD;
    private javax.swing.JPanel Panel_button_atualizar;
    private javax.swing.JPanel Panel_button_autorizacao;
    private javax.swing.JPanel Panel_button_criar;
    private javax.swing.JPanel Panel_button_deletar;
    private javax.swing.JPanel Panel_button_feedbacks;
    private javax.swing.JPanel Panel_button_materiais;
    private javax.swing.JPanel Panel_button_sair;
    private javax.swing.JPanel Panel_confirmar_atualizar_material;
    private javax.swing.JPanel Panel_confirmar_criar_material;
    private javax.swing.JPanel Panel_confirmar_deletar_material;
    private javax.swing.JPanel Panel_criar;
    private javax.swing.JPanel Panel_criar_voltar_material;
    private javax.swing.JPanel Panel_deletar;
    private javax.swing.JPanel Panel_voltar_atualizar_material;
    private javax.swing.JPanel Panel_voltar_deletar_material;
    private javax.swing.JLabel button_atualizar;
    private javax.swing.JLabel button_autorizacao;
    private javax.swing.JLabel button_criar;
    private javax.swing.JLabel button_deletar;
    private javax.swing.JLabel button_feedbacks;
    private javax.swing.JLabel button_hide_menu;
    private javax.swing.JLabel button_materiais;
    private javax.swing.JLabel button_max;
    private javax.swing.JPanel button_min;
    private javax.swing.JLabel button_sair;
    private javax.swing.JLabel button_voltar;
    private javax.swing.JLabel button_voltar1;
    private javax.swing.JPanel close_panel;
    private javax.swing.JPanel header_icon;
    private javax.swing.JLabel icon_label_maua;
    private javax.swing.JPanel icone_min_max_close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel max_panel;
    private javax.swing.JPanel panel_barra_menu;
    private javax.swing.JPanel panel_hide_menu;
    private javax.swing.JTextField textfield_IDMaterial;
    private javax.swing.JTextField textfield_IDMaterial1;
    private javax.swing.JTextField textfield_IDMaterial2;
    private javax.swing.JTextField textfield_IDMaterial3;
    private javax.swing.JTextField textfield_NomeMaterial;
    private javax.swing.JTextField textfield_NomeMaterial1;
    private javax.swing.JTextField textfield_Quantidade;
    private javax.swing.JTextField textfield_Quantidade1;
    private javax.swing.JTextField textfield_QuantidadeDisp;
    private javax.swing.JTextField textfield_QuantidadeDisp1;
    // End of variables declaration//GEN-END:variables
}
